CREATE TABLE tb_venda_compra_virtual(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pessoa_id INTEGER,
  endereco_entrega_id INTEGER NOT NULL,
  endereco_cobranca_id INTEGER,
  valor_total DECIMAL(10,2),
  valor_desconto DECIMAL(10,2),
  forma_pagamento_id INTEGER,
  nota_fiscal_venda_id INTEGER,
  cupom_desconto_id INTEGER,
  valor_frete DECIMAL(10,2),
  dias_entrega INTEGER,
  data_venda DATE,
  url_imprime_etiqueta VARCHAR(350),
  status_venda_loja_virtual VARCHAR CHECK (status_venda_loja_virtual IN ('Finalizada' , 'Cancelada' , 'Abandonou Carrinho')),
  
  CONSTRAINT fk_pessoa FOREIGN KEY(pessoa_id) REFERENCES tb_pessoa(id),
  CONSTRAINT fk_endereco_entrega FOREIGN KEY(endereco_entrega_id) REFERENCES tb_endereco(id),
  CONSTRAINT fk_endereco_cobranca FOREIGN KEY(endereco_cobranca_id) REFERENCES tb_endereco(id),
  CONSTRAINT fk_forma_pagamento FOREIGN KEY(forma_pagamento_id) REFERENCES tb_forma_pagam(id),
  CONSTRAINT fk_cupom_desconto FOREIGN KEY(cupom_desconto_id) REFERENCES tb_cupom_desconto(id)
);