CREATE TABLE tb_Nota_fiscal_venda(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero VARCHAR(250) NOT NULL,
  serie VARCHAR(300) NOT NULL,
  tipo VARCHAR(300) NOT NULL,
  xml TEXT,
  pdf TEXT,
  empresa_id INTEGER,
  
  CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);

-- Alterando a tabela 'tb_venda_compra_virtual' para adicionar a restrição UNIQUE na coluna 'nota_fiscal_venda_id'
ALTER TABLE tb_venda_compra_virtual 
ADD CONSTRAINT unique_nota_fiscal_venda_id UNIQUE (nota_fiscal_venda_id);

-- Adicionando a chave estrangeira
ALTER TABLE tb_venda_compra_virtual 
ADD CONSTRAINT fk_nota_fiscal_venda FOREIGN KEY (nota_fiscal_venda_id) 
REFERENCES tb_Nota_fiscal_venda(id);
