CREATE TABLE tb_imagem_produto(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 imagem_original VARCHAR(250) NOT NULL,
 imagem_miniatura VARCHAR(250) NOT NULL,
 link_tou_tuber VARCHAR(250) NOT NULL,
 produto_id INTEGER,
 empresa_id INTEGER,

 CONSTRAINT fk_produto FOREIGN KEY(produto_id) REFERENCES tb_produto(id),
 CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);