CREATE TABLE tb_avaliacao_produto(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nota INTEGER,
 descricao TEXT,
 pessoa_id INTEGER,
 produto_id INTEGER,
 empresa_id INTEGER,

 CONSTRAINT fk_pessoa FOREIGN KEY(pessoa_id) REFERENCES tb_pessoa(id),
 CONSTRAINT fk_produto FOREIGN KEY(produto_id) REFERENCES tb_produto(id),
 CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);