CREATE TABLE tb_conta_pagar(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(400),
  valor_total DECIMAL(10,2),
  valor_desconto DECIMAL(10,2),
  dt_vencimento DATE,
  dt_pagamento DATE,
  status VARCHAR(50) CHECK (status IN ('Pagar', 'Vencida', 'Aberta', 'Quitada')),
  pessoa_fornecedor_id INTEGER,
  empresa_id INTEGER,
  nota_fiscal_compra_id INTEGER,
  endereco_id INTEGER,

  CONSTRAINT fk_pessoa_fornecedor FOREIGN KEY(pessoa_fornecedor_id) REFERENCES tb_pessoa_juridica(id),
  CONSTRAINT fk_empresa_conta_pagar FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id),
  CONSTRAINT fk_nota_fiscal_compra_conta FOREIGN KEY(nota_fiscal_compra_id) REFERENCES tb_nota_fiscal_compra(id),
  CONSTRAINT fk_endereco_conta_pagar FOREIGN KEY(endereco_id) REFERENCES tb_endereco(id)
);
