CREATE TABLE tb_pessoa(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  telefone VARCHAR(250) NOT NULL
);

ALTER TABLE tb_usuario ADD COLUMN pessoa_id INTEGER;
ALTER TABLE tb_usuario ADD CONSTRAINT fk_pessoa FOREIGN KEY(pessoa_id) REFERENCES tb_pessoa(id);

CREATE TABLE tb_pessoa_fisica(
  id INTEGER PRIMARY KEY,
  cpf VARCHAR(250) NOT NULL,
  data_nascimento DATE NOT NULL
);

CREATE TABLE tb_pessoa_juridica (
  id INTEGER PRIMARY KEY,
  cnpj VARCHAR(250) NOT NULL,
  insc_estadual VARCHAR(250) NOT NULL,
  insc_municipal VARCHAR(250) NOT NULL,
  nome_fantasia VARCHAR(250) NOT NULL,
  razao_social VARCHAR(250) NOT NULL
);

ALTER TABLE tb_usuario ADD COLUMN empresa_id INTEGER;
ALTER TABLE tb_usuario ADD CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id);