CREATE TABLE tb_categoria_produto(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome_desc VARCHAR(250) NOT NULL,
 empresa_id INTEGER,
 CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);