CREATE TABLE tb_cupom_desconto(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cod_desc VARCHAR(250) NOT NULL,
 valor_realdesc DECIMAL NOT NULL,
 valor_porcentDesc DECIMAL NOT NULL,
 data_criada DATE,
 data_validade DATE,
 empresa_id INTEGER,
 CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);