spring.application.name=lojaVirtualEnvioEmail
server.port=9090

spring.kafka.bootstrapServers=localhost:19092
spring.kafka.properties.schema.registry.url=http://localhost:8081

spring.kafka.topico-boleto=solicitacao-lojaVirtualEnvioEmail
spring.kafka.topico-notificacao=notificacao-lojaVirtualEnvioEmail
spring.kafka.properties.specific.avro.reader=true
spring.kafka.consumer.group-id=api-lojaVirtual

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true

spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=200
spring.datasource.hikari.maximum-pool-size=550
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.pool-name=PoolHikari

spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
