CREATE TABLE tb_nota_fiscal_compra(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_nota VARCHAR(250) NOT NULL,
  serie_nota VARCHAR(300) NOT NULL,
  descricao_ods VARCHAR(300) NOT NULL,
  valor_total DECIMAL(10,2),
  valor_desconto DECIMAL(10,2),
  valor_icms DECIMAL(10,2),
  data_compra TIMESTAMP,
  pessoa_id INTEGER,
  empresa_id INTEGER,
  CONSTRAINT fk_pessoa FOREIGN KEY(pessoa_id) REFERENCES tb_pessoa(id),
  CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);