CREATE TABLE tb_produto(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tipo_unidade VARCHAR(250) NOT NULL,
 nome VARCHAR(250) NOT NULL,
 descricao TEXT,
 ativo BOOLEAN,
 peso DECIMAL(10,2),
 largura DECIMAL(10,2),
 autura DECIMAL(10,2),
 profundidade DECIMAL(10,2),
 valor_venda DECIMAL(10,2),
 qtd_estoque INTEGER,
 qtde_aleta_estoque INTEGER,
 alerta_qtd_estoque BOOLEAN,
 qtde_clique INTEGER,
 marca_produto_id INTEGER,
 categoria_produto_id INTEGER,
 empresa_id INTEGER,
 
 CONSTRAINT fk_marca_produto FOREIGN KEY(marca_produto_id) REFERENCES tb_marca_produto(id),
 CONSTRAINT fk_categoria_produto FOREIGN KEY(categoria_produto_id) REFERENCES tb_categoria_produto(id),
 CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);