CREATE TABLE tb_status_rastreio(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 venda_compra_virtual_id INTEGER,
 empresa_id INTEGER,

 CONSTRAINT fk_venda_compra_virtual FOREIGN KEY(venda_compra_virtual_id) REFERENCES tb_venda_compra_virtual(id),
 CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);