CREATE TABLE tb_nota_item_produto(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 quantidade DECIMAL(10,2),
 nota_fiscal_compra_id INTEGER,
 produto_id INTEGER,

 CONSTRAINT fk_nota_fiscal_compra FOREIGN KEY(nota_fiscal_compra_id) REFERENCES tb_nota_fiscal_compra(id),
 CONSTRAINT fk_produto FOREIGN KEY(produto_id) REFERENCES tb_produto(id)
);