
CREATE TABLE IF NOT EXISTS public.pessoa
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    telefone character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT pessoa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_acesso
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tb_acesso_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_avaliacao_produto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    nota integer,
    empresa_id bigint,
    pessoa_id bigint,
    produto_id bigint,
    CONSTRAINT tb_avaliacao_produto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_categoria_produto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_desc character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tb_categoria_produto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_conta_pagar
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    dt_pagamento date,
    dt_vencimento date,
    status character varying(255) COLLATE pg_catalog."default",
    valor_desconto numeric(38, 2),
    valortotal numeric(38, 2),
    empresa_id bigint,
    endereco_id bigint,
    nota_fiscal_compra_id bigint,
    pessoa_id bigint,
    pessoa_fornecedo_id bigint,
    CONSTRAINT tb_conta_pagar_pkey PRIMARY KEY (id),
    CONSTRAINT uk11nlblv8ewns0c7t8n8huk841 UNIQUE (nota_fiscal_compra_id)
);

CREATE TABLE IF NOT EXISTS public.tb_conta_receber
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    dt_pagamento date,
    dt_vencimento date,
    status character varying(255) COLLATE pg_catalog."default",
    valor_descontos numeric(38, 2),
    valortotal numeric(38, 2),
    empresa_id bigint,
    pessoa_id bigint,
    CONSTRAINT tb_conta_receber_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_cupom_desconto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cod_desc character varying(255) COLLATE pg_catalog."default",
    data_criada date,
    data_validade date,
    valor_porcent_desc numeric(38, 2),
    valor_realdesc numeric(38, 2),
    empresa_id bigint,
    CONSTRAINT tb_cupom_desconto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_endereco
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bairro character varying(255) COLLATE pg_catalog."default",
    cep character varying(255) COLLATE pg_catalog."default",
    cidade character varying(255) COLLATE pg_catalog."default",
    complemento character varying(255) COLLATE pg_catalog."default",
    estado character varying(255) COLLATE pg_catalog."default",
    numero character varying(255) COLLATE pg_catalog."default",
    rua_logra character varying(255) COLLATE pg_catalog."default",
    tipo_endereco character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uf character varying(255) COLLATE pg_catalog."default",
    empresa_id bigint,
    pessoa_id bigint,
    CONSTRAINT tb_endereco_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_forma_pagam
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    descricao character varying(255) COLLATE pg_catalog."default",
    empresa_id bigint,
    CONSTRAINT tb_forma_pagam_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_imagem_produto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    imagem_miniatura text COLLATE pg_catalog."default",
    imagem_original text COLLATE pg_catalog."default",
    link_tou_tuber character varying(255) COLLATE pg_catalog."default",
    produto_id bigint,
    CONSTRAINT tb_imagem_produto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_item_venda_loja
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    quantidade double precision,
    produto_id bigint,
    venda_compra_virtual_id bigint,
    CONSTRAINT tb_item_venda_loja_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_marca_produto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_desc character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tb_marca_produto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_nota_fiscal_compra
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_compra timestamp(6) with time zone,
    descricao_ods character varying(255) COLLATE pg_catalog."default",
    numero_nota character varying(255) COLLATE pg_catalog."default",
    serie_nota character varying(255) COLLATE pg_catalog."default",
    valor_desconto numeric(38, 2),
    valor_icms numeric(38, 2),
    valor_total numeric(38, 2),
    quantidade double precision,
    pessoa_id bigint,
    nota_fiscal_compra_id bigint,
    produto_id bigint,
    CONSTRAINT tb_nota_fiscal_compra_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_nota_fiscal_venda
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero character varying(255) COLLATE pg_catalog."default",
    pdf text COLLATE pg_catalog."default",
    serie character varying(255) COLLATE pg_catalog."default",
    tipo character varying(255) COLLATE pg_catalog."default",
    xml text COLLATE pg_catalog."default",
    venda_compra_virtual_id bigint,
    CONSTRAINT tb_nota_fiscal_venda_pkey PRIMARY KEY (id),
    CONSTRAINT ukf0s5k3jqeauay2vcba98x9ahs UNIQUE (venda_compra_virtual_id)
);

CREATE TABLE IF NOT EXISTS public.tb_pessoa_fisica
(
    cpf character varying(255) COLLATE pg_catalog."default",
    data_nascimento date,
    id bigint NOT NULL,
    CONSTRAINT tb_pessoa_fisica_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_pessoa_juridica
(
    cnpj character varying(255) COLLATE pg_catalog."default",
    insc_estadual character varying(255) COLLATE pg_catalog."default",
    insc_municipal character varying(255) COLLATE pg_catalog."default",
    nome_fantasia character varying(255) COLLATE pg_catalog."default",
    razao_social character varying(255) COLLATE pg_catalog."default",
    id bigint NOT NULL,
    CONSTRAINT tb_pessoa_juridica_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_produto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    alerta_qtd_estoque boolean,
    ativo boolean,
    autura double precision,
    descricao text COLLATE pg_catalog."default",
    largura double precision,
    nome character varying(255) COLLATE pg_catalog."default",
    peso double precision,
    profundidade double precision,
    qtd_cliente integer,
    qtd_estoque integer,
    qtde_aleta_estoque integer,
    tipo_unidade character varying(255) COLLATE pg_catalog."default",
    valor_venda numeric(38, 2),
    categoria_produto_id bigint,
    marca_produto_id bigint,
    nota_item_produto bigint,
    CONSTRAINT tb_produto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_status_rastreio
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    empresa_id bigint,
    venda_compra_virtual_id bigint,
    CONSTRAINT tb_status_rastreio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_atua_senha date,
    login character varying(255) COLLATE pg_catalog."default",
    senha character varying(255) COLLATE pg_catalog."default",
    pessoa_id bigint,
    CONSTRAINT tb_usuario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tb_usuario_acessos
(
    usuario_id bigint NOT NULL,
    acessos_id bigint NOT NULL,
    CONSTRAINT ukon8ks0hoqmllgy9yhgajrpisq UNIQUE (acessos_id)
);

CREATE TABLE IF NOT EXISTS public.tb_venda_compra_virtual
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_venda date,
    dias_entrega integer,
    status_venda_loja_virtual character varying(255) COLLATE pg_catalog."default",
    url_imprime_etiqueta character varying(255) COLLATE pg_catalog."default",
    valor_desconto numeric(38, 2),
    valor_frete numeric(38, 2),
    valor_total numeric(38, 2),
    cupom_desconto_id bigint,
    endereco_cobranca_id bigint,
    endereco_entrega_id bigint,
    forma_pagamento_id bigint,
    nota_fiscal_venda_id bigint,
    pessoa_id bigint,
    CONSTRAINT tb_venda_compra_virtual_pkey PRIMARY KEY (id)
);
