CREATE TABLE tb_conta_receber(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao VARCHAR(400),
  status VARCHAR(50) CHECK (status IN ('Receber', 'Vencida', 'Aberta', 'Quitada' , 'Renegociada')),
  dt_vencimento DATE,
  dt_pagamento DATE,
  valor_total DECIMAL(10,2),
  valor_descontos DECIMAL(10,2),
  pessoa_id INTEGER,
  empresa_id INTEGER,

  CONSTRAINT fk_pessoa FOREIGN KEY(pessoa_id) REFERENCES tb_pessoa(id),
  CONSTRAINT fk_empresa FOREIGN KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);
