CREATE TABLE tb_usuario(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR(255) NOT NULL,
  senha VARCHAR(300) NOT NULL,
  data_atuaSenha DATE NOT NULL
);

CREATE TABLE tb_usuario_acesso(
  usuario_id INTEGER NOT NULL,
  acesso_id INTEGER NOT NULL,
  PRIMARY KEY(usuario_id , acesso_id),
  CONSTRAINT fk_usuario FOREIGN KEY(usuario_id) REFERENCES tb_usuario(id),
  CONSTRAINT fk_acesso FOREIGN KEY(acesso_id) REFERENCES tb_acesso(id)
);