CREATE TABLE tb_endereco(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rua_logra VARCHAR(500) NOT NULL,
  cep VARCHAR(100) NOT NULL,
  numero VARCHAR(50) NOT NULL,
  complemento VARCHAR(500),
  bairro VARCHAR(250),
  uf VARCHAR(250),
  cidade VARCHAR(250),
  estado VARCHAR(250),
  tipo_endereco VARCHAR(250) CHECK (tipo_endereco IN ('Cobrança' , 'Entrega' , 'Particula' , 'Comercial')),
  empresa_id INTEGER,
  CONSTRAINT fk_empresa FOREIGN  KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);