CREATE TABLE tb_forma_pagam(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 descricao VARCHAR(250) NOT NULL,
 empresa_id INTEGER,
 CONSTRAINT fk_empresa FOREIGN  KEY(empresa_id) REFERENCES tb_pessoa_juridica(id)
);